# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin_grasping.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_admin_grasping(object):
    def setupUi(self, admin_grasping):
        admin_grasping.setObjectName("admin_grasping")
        admin_grasping.resize(390, 402)
        admin_grasping.setStyleSheet("*{    \n"
"    font-family:微软雅黑;\n"
"    font-size:15px;\n"
"    color: #1d649c;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(admin_grasping)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(10, 5, 10, 5)
        self.horizontalLayout.setSpacing(25)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.careful = QtWidgets.QPushButton(self.centralwidget)
        self.careful.setObjectName("careful")
        self.horizontalLayout.addWidget(self.careful)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(5, 15, 15, 15)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.userdta_edite = QtWidgets.QTextEdit(self.centralwidget)
        self.userdta_edite.setObjectName("userdta_edite")
        self.horizontalLayout_2.addWidget(self.userdta_edite)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(148, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.save = QtWidgets.QPushButton(self.centralwidget)
        self.save.setObjectName("save")
        self.horizontalLayout_3.addWidget(self.save)
        spacerItem1 = QtWidgets.QSpacerItem(138, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        admin_grasping.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(admin_grasping)
        self.statusbar.setObjectName("statusbar")
        admin_grasping.setStatusBar(self.statusbar)

        self.retranslateUi(admin_grasping)
        QtCore.QMetaObject.connectSlotsByName(admin_grasping)

    def retranslateUi(self, admin_grasping):
        _translate = QtCore.QCoreApplication.translate
        admin_grasping.setWindowTitle(_translate("admin_grasping", "MainWindow"))
        self.careful.setText(_translate("admin_grasping", "学号 密码 位置 一楼1X开头5楼05开头"))
        self.save.setText(_translate("admin_grasping", "保存"))
