# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'see_seat.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_see_seat(object):
    def setupUi(self, see_seat):
        see_seat.setObjectName("see_seat")
        see_seat.resize(327, 137)
        see_seat.setStyleSheet("*{    \n"
"    font-family:微软雅黑;\n"
"    font-size:15px;\n"
"    color: #1d649c;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(see_seat)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(20, 20, 20, 20)
        self.horizontalLayout.setSpacing(40)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.control1 = QtWidgets.QPushButton(self.centralwidget)
        self.control1.setObjectName("control1")
        self.horizontalLayout.addWidget(self.control1)
        self.control2 = QtWidgets.QPushButton(self.centralwidget)
        self.control2.setObjectName("control2")
        self.horizontalLayout.addWidget(self.control2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        see_seat.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(see_seat)
        self.statusbar.setObjectName("statusbar")
        see_seat.setStatusBar(self.statusbar)

        self.retranslateUi(see_seat)
        QtCore.QMetaObject.connectSlotsByName(see_seat)

    def retranslateUi(self, see_seat):
        _translate = QtCore.QCoreApplication.translate
        see_seat.setWindowTitle(_translate("see_seat", "MainWindow"))
        self.control1.setText(_translate("see_seat", "今天的坑"))
        self.control2.setText(_translate("see_seat", "明天的坑"))
